### ISSUE TITLE
Disable replacement in input fields

### ISSUE THREAD

**Issue by HughxDev** [ericwbailey/millennials-to-snake-people#13]
[Using the abbreviations M and SP to prevent a confusing bug report while the extension is enabled.]

It will trigger while I'm in the middle of typing a comment (as tested on Facebook), and then the cursor shifts to the start of the text, so I have to reposition my cursor and retype the word M and hopefully press Submit before it checks the page again. I want to submit the comment as M, so that people who don't have the extension installed will read it the way it's intended, but I don't mind it displaying as SP once it's posted.

**Comment by pselle** [comment]
cc @ericwbailey Have you looked into this at all? Seems to be a thing with the mutation observer .. those fields aren't native `<input>` fields, which are immune to observation ... ideas?

**Comment by ericwbailey** [comment]
I've been toying with it a little here and there, but frankly it's a little bit beyond my JS abilities at this point, especially if it's a non-native field. 

Honestly, I'd normally be a little more dismissive of the issue because it is a weird exception and I don't want to get in the chasing down every weird comment implementation business, but considering Facebook's size and popularity, it's definitely worth further consideration.

**Comment by pselle** [comment]
Facebook _and_ Google. I'm also curious _how_ they get the input behavior
when it's not an input. That's weird!

**Comment by pselle** [comment]
FYI, being a bit more critical before calling the big replace function removes this issue: https://github.com/pselle/millennials-to-snake-people/commit/725445cac25dce56c88e9cb3fd12b089fa9d5233

**Comment by pselle** [comment]
Oh, actually, this won't fix OP's issue :) but it does fix weird backwards text in FF, maybe that's not happening in Chrome _shrug_

**Comment by ericwbailey** [comment]
Oh, crazy. I haven't encountered that bug yet.

**Comment by ericwbailey** [comment]
I believe https://github.com/ericwbailey/millennials-to-snake-people/pull/24 can (finally) put this issue to rest!
