### ISSUE TITLE
Cursor being moved when typing

### ISSUE THREAD

**Issue by redbassett** [ericwbailey/millennials-to-snake-people#21]
Starting about a week ago, the extension causes my cursor to jump when I type the first character in a new line. On some sites/input boxes (Facebook Chat message fields, the new note field on Google Keep, and the message compose box in Google Inbox, to name a few), the cursor gets moved back to the start of the line when typing the first character on a blank line:

Expected result:
> Hello World

Actual Result:
> ello WorldH

When I type the `H` in a new line, the cursor gets bumped back to the start of the line. If I finish the line and go back, the `H` can be added fine. Running Chrome Dev `58.0.3018.3 (Official Build) dev (64-bit)`

**Comment by ericwbailey** [comment]
Thank you for the detailed issue report. 

I've heard [similar problems happening for non-standard input fields](https://github.com/ericwbailey/millennials-to-snake-people/issues/13), definitely both Google and Facebook are guilty of that. I'll take a look and see what I can do.

**Comment by redbassett** [comment]
I see that you said the non-standard fields were a bit complex. I'll poke around if I get a chance, but unlikely I'll find anything you didn't in there. Certainly annoying that they can't use an normal input underneath…

**Comment by subbes** [comment]
Can  confirm this is occurring with Twitter and with GMail text input fields.

**Comment by SnoopJ** [comment]
I spent a little time playing with this in the [DraftJS editor](https://draftjs.org/) (which is what Facebook uses), and it appears to happen because the extension is watching for **all** changes to the DOM, and performing the value replacement as it walks the *even if there aren't any replacements to make*. I'm not sure what this breaks in the internals of that editor or others, but changing [`handleText()`](https://github.com/ericwbailey/millenials-to-snake-people/blob/master/Source/content_script.js#L18-L20) as below resolves the issue for Facebook and Gmail by only performing the assignment when it is necessary. It's a band-aid solution, but it does resolve the problem on my end (from #13 it seems like maybe this doesn't work across all clients?)

```js
function handleText(textNode) {
  var newval = replaceText(textNode.nodeValue);
  if (textNode.nodeValue !== newval) {
    textNode.nodeValue = newval;
  }
}
```

It doesn't really seem in the spirit of this extension to edit text in input fields, so it seems like putting a condition on the [handling of mutations](https://github.com/ericwbailey/millenials-to-snake-people/blob/master/Source/content_script.js#L249) or [possibly the `NodeFilter` used for the tree](https://github.com/ericwbailey/millenials-to-snake-people/blob/master/Source/content_script.js#L7) would be more appropriate. In the case of DraftJS, the parent of the `<span>` element that causes this bug has a class attribute like `class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"`, so this kind of test seems feasible. In the case of Gmail, the `contenteditable` attribute appears to be explicitly set (and should probably be checked regardless if this excluded case is desired), as well as the `editable` class.

**Comment by flarnie** [comment]
Just came across this and am happy to see a possible fix! Let me know if I can help - I'm not sure if we can adjust anything in Draft.js to make this easier to fix but if so let me know.

**Comment by ericwbailey** [comment]
I'd love some help, @flarnie! There's been some work in https://github.com/ericwbailey/millennials-to-snake-people/pull/22, would you mind giving it your expert opinion?

**Comment by SnoopJ** [comment]
I tested #22 on the machine that exhibited this bug and it did not resolve the backwards-typing issue, although it *does* prevent text from being replaced on input fields which I think is an important feature. 

@ericwbailey I'll see about putting a PR together to ignore DraftJS and the Gmail editable pursuant to my remarks above. @flarnie if you could comment on a best-practices way to identify a node that's associated with DraftJS running on any site with any styling, that'd be a big help! (it seems like checking for e.g. `DraftStyle` contained in the class might be a little fragile)

**Comment by hlmartin** [comment]
Hi, just wanted to report this same issue just started occurring for myself in both Facebook and Twitter input fields. This only started happening yesterday, so I suspect whatever change was in Chrome Dev that the original reporter was affected by is now in mainline. Currently using Chrome Version 58.0.3029.81 (64-bit). Happy to assist in finding a solution!

**Comment by sophiebits** [comment]
@SnoopJeDi Checking if it's contained in a node with the `contenteditable` attribute set seems likely safe enough.
